### Hämta token för user
POST http://localhost:8080/oauth2/token
# user
Authorization: Basic dXNlcjpzZWNyZXQ=
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials &
scope=read

> {% client.global.set("access_token", response.body.access_token); %}

### Anropa skyddad endpoint /hello som user
GET http://localhost:8080/api/hello
Authorization: Bearer {{access_token}}

### Anropa skyddad endpoint /user/data som user
GET http://localhost:8080/api/user/data
Authorization: Bearer {{access_token}}

### Anropa skyddad endpoint /admin/data som user
GET http://localhost:8080/api/admin/data
Authorization: Bearer {{access_token}}



### Hämta token för admin
POST http://localhost:8080/oauth2/token
# admin
Authorization: Basic YWRtaW46c2VjcmV0
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials &
scope=read write

> {% client.global.set("access_token", response.body.access_token); %}

### Anropa skyddad endpoint /hello som admin
GET http://localhost:8080/api/hello
Authorization: Bearer {{access_token}}

### Anropa skyddad endpoint /admin/data som admin
GET http://localhost:8080/api/admin/data
Authorization: Bearer {{access_token}}
